version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
    commands:
      - echo "Installing composer dependencies..."
      - composer install --no-dev --optimize-autoloader

  pre_build:
    commands:
      - echo "Creating Laravel cache directories..."
      - mkdir -p bootstrap/cache
      - mkdir -p storage/framework/cache
      - mkdir -p storage/framework/sessions
      - mkdir -p storage/framework/views
      - chmod -R 775 storage bootstrap/cache

      - echo "Checking folder permissions and existence"
      - ls -la storage/framework/
      - ls -la storage/framework/views
      - ls -la bootstrap/cache

      - echo "Copying .env file"
      - cp .env.example .env || true

      - echo "Running artisan commands"
      - php artisan package:discover
      - php artisan config:cache
      - php artisan route:cache
      - php artisan view:cache

  build:
    commands:
      - echo "Build complete. Ready to deploy."

artifacts:
  files:
    - '**/*'
    - '!**/node_modules/**'
    - '!**/tests/**'
