version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
    commands:
      - echo "Creating Laravel required directories..."
      - mkdir -p bootstrap/cache
      - mkdir -p storage/framework/{cache,sessions,views}
      - chmod -R 775 storage bootstrap/cache

      - echo "Installing composer dependencies..."
      - composer install --no-dev --optimize-autoloader

  pre_build:
    commands:
      - echo "Setting up environment..."
      - cp .env.example .env || echo ".env already exists"
      - php artisan config:cache || true
      - php artisan route:cache || true
      - php artisan view:cache || true

  build:
    commands:
      - echo "Build complete."

artifacts:
  files:
    - '**/*'
    - '!**/node_modules/**'
    - '!**/tests/**'
