# buildspec.yml - AWS CodeBuild configuration
version: 0.2

phases:
  pre_build:
    commands:
      - echo "Pre-build phase started on `date`"
      - echo "Creating Laravel storage directories..."
      # Create all required Laravel directories BEFORE composer install
      - mkdir -p storage/app/public
      - mkdir -p storage/framework/cache/data
      - mkdir -p storage/framework/sessions
      - mkdir -p storage/framework/testing
      - mkdir -p storage/framework/views
      - mkdir -p storage/logs
      - mkdir -p bootstrap/cache
      # Set permissions
      - chmod -R 775 storage
      - chmod -R 775 bootstrap/cache
      # Create .env file
      - cp .env.example .env
      
  build:
    commands:
      - echo "Build phase started on `date`"
      # Install composer dependencies WITHOUT running post-install scripts
      - composer install --no-scripts --no-dev --optimize-autoloader
      # Now manually run the autoloader generation
      - composer dump-autoload --optimize
      # Generate application key
      - php artisan key:generate --force
      # Run package discovery manually (now that directories exist)
      - php artisan package:discover --ansi
      # Clear caches
      - php artisan config:clear
      - php artisan cache:clear
      - php artisan view:clear
      # Install NPM dependencies if needed
      - npm ci --only=production
      # Build assets if needed
      - npm run production
      
  post_build:
    commands:
      - echo "Post-build phase started on `date`"
      - echo "Build completed successfully"

artifacts:
  files:
    - '**/*'
  name: laravel-app-$(date +%Y-%m-%d)

cache:
  paths:
    - 'vendor/**/*'
    - 'node_modules/**/*'
