phases:
  install:
    runtime-versions:
      php: 8.1
    commands:
      - echo "Installing dependencies..."
      - composer install
  pre_build:
    commands:
      - echo "Creating Laravel cache directories..."
      - mkdir -p storage/framework/cache
      - mkdir -p storage/framework/sessions
      - mkdir -p storage/framework/views
  build:
    commands:
      - php artisan config:cache
      - php artisan route:cache
      - php artisan view:cache
