version: 0.2
phases:
  install:
    runtime-versions:
      php: 8.2
    commands:
      - echo "Installing dependencies without scripts..."
      - COMPOSER_ALLOW_SUPERUSER=1 composer install --no-dev --optimize-autoloader --no-scripts
      - echo "Running post-install scripts..."
      - COMPOSER_ALLOW_SUPERUSER=1 composer run-script post-install-cmd || echo "Post-install scripts completed with warnings"
  pre_build:
    commands:
      - echo "Ensuring Laravel cache folders exist and are writable..."
      - mkdir -p bootstrap/cache
      - mkdir -p storage/framework/views
      - mkdir -p storage/framework/cache
      - mkdir -p storage/framework/sessions
      - chmod -R 775 storage bootstrap/cache
      - echo "Checking folder permissions and existence"
      - ls -la storage/framework/
      - ls -la storage/framework/views
      - ls -la bootstrap/cache
      - echo "Copying .env file"
      - cp .env.example .env || true
      - echo "Running artisan commands"
      - php artisan package:discover
      - echo "Publishing Jetstream resources if needed..."
      - php artisan vendor:publish --tag=jetstream-views --force || echo "Jetstream views not found, skipping..."
      - php artisan config:cache
      - php artisan route:cache
      - echo "Attempting to cache views..."
      - php artisan view:cache || echo "View caching failed, continuing without view cache..."
  build:
    commands:
      - echo "Laravel app is now built and ready to deploy."
artifacts:
  files:
    - '**/*'
    - '!**/node_modules/**'
    - '!**/tests/**'
