# Copy environment file
cp .env.example .env

# Install PHP dependencies
composer install

# Generate application key
php artisan key:generate

# Create storage directories
mkdir -p storage/framework/{views,cache,sessions}
chmod -R 775 storage bootstrap/cache

# Clear caches
php artisan config:clear
php artisan cache:clear

# Install NPM dependencies
npm install

# Serve the application
php artisan serve
