version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
    commands:
      - echo "Creating Laravel directories..."
      - mkdir -p bootstrap/cache
      - mkdir -p storage/framework/{cache,sessions,views}
      - chmod -R 775 storage bootstrap/cache

      - echo "Installing dependencies without post-autoload scripts..."
      - COMPOSER_ALLOW_SUPERUSER=1 composer install --no-dev --optimize-autoloader --no-scripts

  pre_build:
    commands:
      - echo "Setting up environment..."
      - cp .env.example .env || true
      - php artisan package:discover
      - php artisan config:cache
      - php artisan route:cache
      - php artisan view:cache

  build:
    commands:
      - echo "Build complete."

artifacts:
  files:
    - '**/*'
    - '!**/node_modules/**'
    - '!**/tests/**'
