version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
    commands:
      - echo "Creating required Laravel directories..."
      - mkdir -p bootstrap/cache
      - mkdir -p storage/framework/{cache,sessions,views}
      - chmod -R 775 storage bootstrap/cache

      - echo "Installing Composer dependencies..."
      - composer install --no-dev --optimize-autoloader

  pre_build:
    commands:
      - echo "Copying .env and caching config..."
      - cp .env.example .env || echo ".env.example missing or .env already exists"
      - php artisan config:cache
      - php artisan route:cache
      - php artisan view:cache

  build:
    commands:
      - echo "Build phase completed."

artifacts:
  files:
    - '**/*'
    - '!**/node_modules/**'
    - '!**/tests/**'
