name: Laravel-deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, curl, xml, intl, zip, pdo, pdo_mysql
          tools: composer

      - name: Prepare Laravel project
        run: |
          mkdir -p bootstrap/cache
          mkdir -p storage/framework/{sessions,views,cache}
          mkdir -p storage/logs
          composer install --no-dev --optimize-autoloader
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      - name: Create deployment zip
        run: zip -r deploy.zip . -x ".git/*" "tests/*" "node_modules/*"

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: efiling_new
          environment_name: Efilingnew-env
          existing_bucket_name: elasticbeanstalk-eu-north-1-953491815896
          region: eu-north-1
          version_label: deploy-${{ github.run_id }}-${{ github.run_number }}-$(date +%Y%m%d%H%M%S)
          deployment_package: deploy.zip
