name: Publish image to Azure
on:
#   pull_request:
#     types: [ closed ]
  push:
    branches:
      - master

jobs:
  laravel-tests:
    runs-on: ubuntu-20.04
    # if: github.event.pull_request.merged == true
    steps:
      - uses: shivammathur/setup-php@master
        with:
          php-version: '8.1'
          extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml
      - uses: actions/checkout@v2
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
        
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      # - name: Execute tests (Unit and Feature tests) via PHPUnit
      #   env:
      #     DB_CONNECTION: sqlite
      #     DB_DATABASE: database/database.sqlite
      #   run: vendor/bin/phpunit
      
  push_to_registries:
    needs: laravel-tests
#     if: github.event.pull_request.merged == true
    name: Build and push containers
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
# login into the azure container registry
      - name: Login to Azure Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      
      - name: Build and push e-filing-master
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/e-filing-master:latest #check up on tagging the app
          push: true
