name: Laravel-deployment
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: efiling_new
          environment_name: Efilingnew-env
          existing_bucket_name: elasticbeanstalk-eu-north-1-953491815896
          region: eu-north-1
          version_label: 4638df31e533c541acc148e920280248d2d1e6b1
          # Note: deployment_package is removed to deploy existing version
