name: Laravel-deployment
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: List files before cleanup
        run: ls -la
        
      - name: Clean up unnecessary files
        run: |
          # Remove files that might trigger composer
          rm -rf vendor/
          rm -rf node_modules/
          # Don't remove composer.json or .lock as EB needs them
          # Remove development files
          rm -rf tests/
          rm -f phpunit.xml*
          rm -f webpack.mix.js
          rm -f package*.json
          rm -f yarn.lock
          
      - name: List files after cleanup  
        run: ls -la
        
      - name: Create deployment package
        run: |
          zip -r deploy.zip . \
            -x "*.git*" \
            -x ".env*" \
            -x "storage/logs/*"
            
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: efiling_new
          environment_name: Efilingnew-env
          existing_bucket_name: elasticbeanstalk-eu-north-1-953491815896
          version_label: ${{ github.sha }}
          region: eu-north-1
          deployment_package: deploy.zip
