name: Laravel-deployment
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: List files before cleanup
        run: ls -la
        
      - name: Install production dependencies
        run: |
          # Install production dependencies first
          composer install --no-dev --optimize-autoloader
          
      - name: Clean up unnecessary files
        run: |
          # Remove development files but keep vendor/
          rm -rf node_modules/
          rm -rf tests/
          rm -f phpunit.xml*
          rm -f webpack.mix.js
          rm -f package*.json
          rm -f yarn.lock
          
      - name: Create Laravel directories and .gitkeep files
        run: |
          # Create required Laravel directories
          mkdir -p bootstrap/cache
          mkdir -p storage/app/public
          mkdir -p storage/framework/cache/data
          mkdir -p storage/framework/sessions
          mkdir -p storage/framework/testing
          mkdir -p storage/framework/views
          mkdir -p storage/logs
          
          # Create .gitkeep files to ensure directories exist in deployment
          touch bootstrap/cache/.gitkeep
          touch storage/app/.gitkeep
          touch storage/app/public/.gitkeep
          touch storage/framework/.gitkeep
          touch storage/framework/cache/.gitkeep
          touch storage/framework/cache/data/.gitkeep
          touch storage/framework/sessions/.gitkeep
          touch storage/framework/testing/.gitkeep
          touch storage/framework/views/.gitkeep
          touch storage/logs/.gitkeep
          
      - name: List files after cleanup  
        run: ls -la
        
      - name: Create deployment package
        run: |
          zip -r deploy.zip . \
            -x "*.git*" \
            -x ".env*" \
            -x "storage/logs/*"
            
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: efiling_new
          environment_name: Efilingnew-env
          existing_bucket_name: elasticbeanstalk-eu-north-1-953491815896
          version_label: ${{ github.sha }}
          region: eu-north-1
          deployment_package: deploy.zip
