name: Laravel-deployment
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ubuntu:20.04
    steps:
      - name: Install basic tools
        run: |
          apt-get update
          apt-get install -y zip git
          
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          clean: true
          
      - name: Remove all potentially problematic files
        run: |
          rm -rf vendor/ || true
          rm -rf node_modules/ || true
          rm -f composer.lock || true
          rm -f composer.phar || true
          find . -name "composer" -type f -delete || true
          
      - name: Create deployment package
        run: |
          zip -r deploy.zip . \
            -x "*.git*" \
            -x ".env*" \
            -x "storage/logs/*" \
            -x "tests/*" \
            -x "*.md"
            
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: efiling_new
          environment_name: Efilingnew-env
          existing_bucket_name: elasticbeanstalk-eu-north-1-953491815896
          version_label: ${{ github.sha }}
          region: eu-north-1
          deployment_package: deploy.zip
