name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, bcmath, curl, xml, intl, zip, pdo, pdo_mysql
          tools: composer

      - name: Prepare Laravel cache directories
        run: |
          mkdir -p bootstrap/cache
          mkdir -p storage/framework/cache
          mkdir -p storage/framework/sessions
          mkdir -p storage/framework/views

      - name: Set correct permissions
        run: chmod -R 755 storage bootstrap/cache

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Generate application key
        run: php artisan key:generate

      # Optional: Add DB setup and test running if needed
      # - name: Run Laravel tests
      #   run: php artisan test
