name: Laravel-deployment
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Prepare deployment package  
        run: |
          # Remove any existing vendor directory
          rm -rf vendor
          rm -rf node_modules
          # Create deployment package excluding development files
          zip -r deploy.zip . \
            -x "*.git*" \
            -x "node_modules/*" \
            -x "tests/*" \
            -x "*.md" \
            -x "phpunit.xml*" \
            -x "webpack.mix.js" \
            -x "package.json" \
            -x "package-lock.json" \
            -x "yarn.lock" \
            -x "vendor/*" \
            -x ".env" \
            -x "storage/logs/*"
            
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: efiling_new
          environment_name: Efilingnew-env
          existing_bucket_name: elasticbeanstalk-eu-north-1-953491815896
          version_label: ${{ github.sha }}
          region: eu-north-1
          deployment_package: deploy.zip
          wait_for_environment_recovery: 300
