name: SonarCloud Analysis

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: e_filing
          MYSQL_USER: laravel
          MYSQL_PASSWORD: secret
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install PHP dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Node.js dependencies
        run: npm ci

      - name: Prepare Laravel
        run: |
          cp .env.example .env
          sed -i 's/DB_HOST=mysql/DB_HOST=127.0.0.1/' .env
          sed -i 's/DB_USERNAME=sail/DB_USERNAME=laravel/' .env
          sed -i 's/DB_PASSWORD=password/DB_PASSWORD=secret/' .env
          php artisan key:generate
          php artisan migrate --force

      - name: Run Tests and Generate Coverage Report
        run: |
          php artisan migrate:fresh --seed
          ./vendor/bin/phpunit --coverage-clover=coverage.xml --debug
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: e_filing
          DB_USERNAME: laravel
          DB_PASSWORD: secret

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
